SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `pevstore` DEFAULT CHARACTER SET utf8 ;
USE `pevstore` ;

CREATE TABLE IF NOT EXISTS `pevstore`.`Pessoa` (
  `cpf` VARCHAR(14) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `dataNascimento` DATE NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `eAdmin` TINYINT(1) NULL DEFAULT 0,
  `senha` VARCHAR(45) NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  UNIQUE INDEX (`email`),
  PRIMARY KEY (`id`),
  UNIQUE INDEX (`cpf`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `pevstore`.`Transportadora` (
  `idTransportadora` INT NOT NULL AUTO_INCREMENT,
  `cnpjTransportadora` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTransportadora`),
  UNIQUE INDEX  (`cnpjTransportadora`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `pevstore`.`Fornecedor` (
  `cnpjFornecedor` VARCHAR(14) NOT NULL,
  `nome` VARCHAR(80) NOT NULL,
  `idFornecedor` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idFornecedor`),
  UNIQUE INDEX (`cnpjFornecedor` ASC))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `pevstore`.`Produto` (
  `codProduto` INT NOT NULL AUTO_INCREMENT,
  `precoCompra` DECIMAL(8,2) NULL,
  `precoVenda` DECIMAL(8,2) NULL,
  `idFornecedor` INT NOT NULL,
  `qtd` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codProduto`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `pevstore`.`Compra` (
  `idCompra` INT NOT NULL AUTO_INCREMENT,
  `dataPedido` DATE NOT NULL,
  `Pessoa_id` INT NOT NULL,
  `idTransportadora` INT NOT NULL,
  `codProduto` INT NOT NULL,
  PRIMARY KEY (`idCompra`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `pevstore`.`Carrinho` (
  `idCarrinho` INT NOT NULL AUTO_INCREMENT,
  `codProduto` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idCarrinho`))
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
